[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
data = { path = "../data" }

[profile.dev]
debug-assertions = false

[profile.release]
debug-assertions = false
panic = "abort"
lto = "thin"
strip = true
